[phases.build]
commands = [
  "npm install --workspaces",
  "npm run build",
  "npm run build:worker"
]

[start]
command = "npm start"

[environment]
node_version = "18.x"

[providers.node]
version = "18.19.1"

[providers.cloudflare]
version = "3.0.0"
[build.cloudflare]
runtime = "nodejs"
entry = ".open-next/worker.js"
include_files = ["worker"]